// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart' as meta;
import 'types.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SessionManager>>
abstract class SessionManager implements RustOpaqueInterface {
  Future<void> clear();

  Future<PersistedVtopSession> exportPersistedSession({
    required String url,
    required String username,
    required BigInt savedAtEpochMs,
  });

  Future<String?> getCookie({required String url});

  Future<ArcJar> getCookieStore();

  Future<String?> getCsrfToken();

  Future<void> importPersistedSession({
    required String url,
    required PersistedVtopSession session,
  });

  Future<bool> isAuthenticated();

  Future<bool> isCookieExternal();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SessionManager> newInstance() =>
      RustLib.instance.api.crateApiVtopSessionManagerSessionManagerNew();

  Future<void> setAuthenticated({required bool authenticated});

  Future<void> setCookieExternal({required bool bool});

  Future<void> setCookieFromExternal({
    required String url,
    required String cookie,
  });

  Future<void> setCsrfFromExternal({required String token});

  Future<void> setCsrfToken({required String token});
}
