// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart' as meta;
import 'session_manager.dart';
import 'types.dart';
import 'vtop_config.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_authenticated_session`, `extract_captcha_data`, `extract_csrf_token`, `extract_javascript_var`, `follow_security_otp_redirect`, `get_login_page_error`, `get_regno`, `is_invalid_credentials_response`, `is_login_url`, `is_security_otp_required_response`, `load_initial_page`, `load_login_page`, `log_auth_event`, `log_cookie_store_state`, `log_network_request`, `login_alert_message`, `make_client`, `mark_session_expired`, `missing_csrf_error`, `normalize_login_alert_message`, `perform_login`, `read_authenticated_response_text`, `reqwest_network_error`, `resolve_vtop_url`, `solve_captcha`, `try_restore_existing_session`, `validate_authenticated_session`, `vtop_server_error`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopClient>>
abstract class VtopClient implements RustOpaqueInterface {
  String get username;

  set username(String username);

  Future<PersistedVtopSession> exportSessionSnapshot({
    required BigInt savedAtEpochMs,
  });

  Future<VtopResultAttendanceData> getAttendance({required String semesterId});

  Future<VtopResultVecU8> getCookie({required bool check});

  Future<VtopResultExamScheduleData> getExamSchedule({
    required String semesterId,
  });

  Future<VtopResultFullAttendanceData> getFullAttendance({
    required String semesterId,
    required String courseId,
    required String courseType,
  });

  Future<VtopResultGradeHistoryData> getGradeHistory();

  Future<VtopResultGradeViewData> getGradeView({required String semesterId});

  Future<VtopResultGradeDetailsData> getGradeViewDetails({
    required String semesterId,
    required String courseId,
  });

  Future<VtopResultMarksData> getMarks({required String semesterId});

  Future<VtopResultSemesterData> getSemesters({required bool check});

  Future<VtopResultTimetableData> getTimetable({required String semesterId});

  Future<bool> isAuthenticated();

  Future<VtopResult> login();

  Future<VtopResult> resendSecurityOtp();

  Future<void> restoreSessionSnapshot({required PersistedVtopSession session});

  Future<void> setCookie({required String cookie});

  Future<VtopResult> submitSecurityOtp({required String otpCode});

  static Future<VtopClient> withConfig({
    required VtopConfig config,
    required SessionManager session,
    required String username,
    required String password,
  }) => RustLib.instance.api.crateApiVtopVtopClientVtopClientWithConfig(
    config: config,
    session: session,
    username: username,
    password: password,
  );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < () >>>
abstract class VtopResult implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < AttendanceData >>>
abstract class VtopResultAttendanceData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < ExamScheduleData >>>
abstract class VtopResultExamScheduleData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < FullAttendanceData >>>
abstract class VtopResultFullAttendanceData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < GradeDetailsData >>>
abstract class VtopResultGradeDetailsData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < GradeHistoryData >>>
abstract class VtopResultGradeHistoryData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < GradeViewData >>>
abstract class VtopResultGradeViewData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < MarksData >>>
abstract class VtopResultMarksData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < SemesterData >>>
abstract class VtopResultSemesterData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < TimetableData >>>
abstract class VtopResultTimetableData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopResult < Vec < u8 > >>>
abstract class VtopResultVecU8 implements RustOpaqueInterface {}
