// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `native_logs_store`, `now_epoch_millis`

Future<void> appendNativeLog({
  required String level,
  required String source,
  required String message,
}) => RustLib.instance.api.crateApiNativeLogsAppendNativeLog(
  level: level,
  source: source,
  message: message,
);

List<String> nativeLogsGetEntries() =>
    RustLib.instance.api.crateApiNativeLogsNativeLogsGetEntries();

void nativeLogsClear() =>
    RustLib.instance.api.crateApiNativeLogsNativeLogsClear();
